spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: Samuel1144
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

